### ISSUE TITLE
The "decline" button doesn't end the call (Firefox/Linux)

### ISSUE THREAD

**Issue by MakisH** [wireapp/wire-webapp#697] opened 2017-01-28 19:38 UTC
![wire-declineproblem](https://cloud.githubusercontent.com/assets/4943683/22399271/79e9614c-e599-11e6-9e07-30b801e8b8a5.png)

Scenario:
1. Alice calls Bob (both from Wire Web, Firefox, Ubuntu)
2. Bob is busy, so he presses "Decline" to reject the call.
3. Alice doesn't see that her call was rejected. Bob still hears his other devices (Android) ringing.

(Firefox 50.1.0, Ubuntu 16.04, Wire 2017-01-27)

**Comment by gregor** [comment] 2017-01-29 18:04
This is actually by design for privacy reasons. Declining a call is a local action to ignore the call. The other side and your other devices will not be notified. We are changing a lot of things in our calling implementation but this will essentially stay the same. Outgoing calls will stop after 30seconds moving forward though. Thereby closing this.

**Closed as completed by gregor** 2017-01-29 18:04 UTC

**Comment by MakisH** [comment] 2017-01-29 18:18
I understand that there may be a good reason to not notify the other side. 

But why should I have my other devices still ringing when I explicitly pressed "decline"? If I am busy, should I go to every device around me and decline the call, so that I stop hearing ringtones? I think this is very unexpected from the user's perspective and it only creates the impression of a bug. From my point of view, the other devices should at least get muted after I press "decline".

**Comment by gregor** [comment] 2017-01-29 23:00
I personally fully agree with you and will forward your concerns to our audio and design teams.
