### ISSUE TITLE
@infotexture ,I cant install wire-webapp in centos version 7.3+ (#7985)

### ISSUE THREAD

**Issue by cgsadmin** [wireapp/wire-webapp#7991] opened 2020-01-04 05:25 UTC
@infotexture ,
I have done changes as per #7987 and it works but now i got new issue again. please help for this 
Please check this in below screen.

![image](https://user-images.githubusercontent.com/20816988/71760222-1cdcb600-2ee0-11ea-82ab-2ea9b79b8913.png)

_Originally posted by @cgsadmin in https://github.com/wireapp/wire-webapp/issues/7985#issuecomment-570758164_

**Comment by cgsadmin** [comment] 2020-01-04 09:06
@typfel ,
I got like this issue also please let me know how to solve this below :

Replace Autoprefixer browsers option to Browserslist config.
[1] Use browserslist key in package.json or .browserslistrc file.
[1]
[1] Using browsers option cause some error. Browserslist config
[1] can be used for Babel, Autoprefixer, postcss-normalize and other tools.
[1]
[1] If you really need to use option, rename it to overrideBrowserslist.
[1]
[1] Learn more at:
[1] https://github.com/browserslist/browserslist#readme
[1] https://twitter.com/browserslist

**Comment by ffflorian** [comment] 2020-01-04 11:08
Duplicate of https://github.com/wireapp/wire-webapp/issues/7985.

**Closed as completed by ffflorian** 2020-01-04 11:08 UTC
Labels: type: feature / request ✨, comp: platform-support, prio: low
