### ISSUE TITLE
"Wire is already open in this browser" after killing chromium

### ISSUE THREAD

**Issue by piegamesde** [wireapp/wire-webapp#5486] opened 2018-12-19 13:14 UTC
## Wire for web version

2018-12-04-14-24

## Browser version

Chromium Version 71.0.3578.98 (Official Build) Arch Linux (64-bit)

## Operating system

Arch Linux

## What steps will reproduce the problem?

1.  Open Wire in a browser and log in.
2.  Crash the PC
3.  Reboot and open chromium again

## What is the expected result?

1. Chromium asks you to restore the crashed pages (Click OK).
2. The Wire tab opens again
3a. I'm still logged in
3b. I got logged out and Wire asks me for the password

(3a and 3b are possible outcomes and mutually exclusive. I'd prefer 3a)

## What is the actual result?

1. Chromium asks to restore the crashed pages
2. The Wire tab opens again
3. "Wire is already open in this browser
If you continue here, you will be logged out on the other tab.
CONTINUE"
![image](https://user-images.githubusercontent.com/14054505/49826011-256ac780-fd86-11e8-973d-c7d8553a4ce5.png)

The workaround from #1440 does not help.

**Comment by piegamesde** [comment] 2018-12-19 13:58
It seems that killing chromium and waiting a few minutes is enough to reproduce it.

**Comment by ffflorian** [comment] 2019-01-07 09:34
Closing as duplicate of https://github.com/wireapp/wire-webapp/issues/4558.

**Closed as completed by ffflorian** 2019-01-07 09:34 UTC
