### ISSUE TITLE
Gifs from Giphy sort option still broken.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-webapp#6147] opened 2019-03-19 18:56 UTC
I reported this 7 months ago, it seems like a signle line of code change.
It's really affecting the moral of the team to not be able to share humor with Wire.

https://github.com/wireapp/wire-webapp/issues/5571

fix https://github.com/wireapp/wire-webapp/pull/4760

**Comment by ffflorian** [comment] 2019-03-20 10:50
Hi @Transisto,

> it seems like a signle line of code change.

Great, can you create a PR which fixes it? If not, I'll close this as duplicate.

**Comment by ffflorian** [comment] 2019-04-08 08:07
Duplicate of https://github.com/wireapp/wire-webapp/issues/5571.

**Closed as completed by ffflorian** 2019-04-08 08:07 UTC
