### ISSUE TITLE
Notifications of liked messages aren't cleared on phone if opened on desktop

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-webapp#1088] opened 2017-04-15 11:38 UTC
See the description in https://github.com/wireapp/wire-android/issues/795. I am unsure whether the problem is the phone or the web app. Feel free to close one of the two tickets depending on where the bug is.

**Comment by gregor** [comment] 2017-04-15 12:01
All messages you see are marked as read on the desktop. If notifications are not cleared on the phone subsequently, the issue is on mobile side.

**Comment by someoneEsle** [comment] 2017-04-15 12:09
`All messages you see are marked as read on the desktop`
? This is not about what messages have been marked as read (in fact the only message involved in this bug is outgoing, not incoming), I'm talking about notifications of liked messages not going way. Not sure which messages "I see" (?). Sorry if my initial message was confusing

**Comment by gregor** [comment] 2017-04-15 12:48
A like is a message as well. Only difference is that it is mapped onto another message. Due to that mobile client could possibly miss the fact that you opened it on desktop.

Will check if we miss to send an update of the read state in this case.

**Comment by gregor** [comment] 2017-08-11 10:30
As I haven't updated this in too long:

We have uncovered the root cause of this issue. It's linked to non-aligned implementations of the use of message timestamps across the different clients teams. We are in the process of addressing this oversight by accumulating the specifications regarding expectation related to effects of timestamps in a single place. It will take a little longer for the actual fix to reach production clients but you an follow the progress at https://github.com/wireapp/wire-webapp/pull/145.

**Comment by someoneEsle** [comment] 2017-08-11 10:37
#145 is probably not the right link (?)

**Comment by gregor** [comment] 2017-08-11 11:08
@someoneEsle Jupp. The last character went missing: https://github.com/wireapp/wire-webapp/pull/1451

**Closed as completed** 2017-09-06 13:05 UTC
Labels: type: bug / fix 🐞
