### ISSUE TITLE
Firefox/Linux: A video call doesn't end completely for the receiver

### ISSUE THREAD

**Issue by MakisH** [wireapp/wire-webapp#687] opened 2017-01-26 17:38 UTC
How to reproduce:
1. Both Alice and Bob use Wire 2017-01-23 on Firefox 50.0.1 on Ubuntu 16.04.
2. Alice starts a video call to Bob (it doesn't matter who starts)
3. Bob answers (with video)
4. Bob sees the video of the conversation normally.
5. Alice ends the call.
6. **Problem:** Bob sees the message view again, but:
  6.1. He can't start a new call to Alice, since the buttons for voice and video call are deactivated.
  6.2. Firefox still shows that the camera and sound are active. The camera LED is on.
7. Bob can call Alice again only if he reloads the page.

![wire 2017-01-26 at 18 12 15](https://cloud.githubusercontent.com/assets/4943683/22342960/7f461c6a-e3f6-11e6-8822-261872418f00.png)

**Comment by gregor** [comment] 2017-01-27 15:22
@MakisH Thank you for your report which we have reproduced internally.

**Comment by gregor** [comment] 2017-03-09 10:14
Seems like we have finally identified the root cause of the issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1233447

A fix is currently in testing https://github.com/wireapp/wire-webapp/pull/861

**Comment by gregor** [comment] 2017-07-09 13:43
@MakisH The intended fix for this has been released to production for a while. I will go ahead and close this issue. Please report if you see this still experience this issue.

**Closed as completed by gregor** 2017-07-09 13:43 UTC
Labels: comp: calling

**Comment by MakisH** [comment] 2017-07-09 13:55
@gregor Indeed, I haven't experienced this for a while. I'm glad for the fix! :-D
