### ISSUE TITLE
Video call Firefox/Linux-to-Firefox/Linux cannot be answered

### ISSUE THREAD

**Issue by MakisH** [wireapp/wire-webapp#685] opened 2017-01-26 11:00 UTC
I just tested it with a partner and we both confirm this problem:

Doesn't work:
- A video call started from Firefox on Linux cannot be picked up from Firefox on Linux. (we tried it both ways) **No "accept"/"decline" buttons are shown.**

Works:
- The same call can be picked up from Android.
- A video call started from Android can be picked up from Firefox on Linux.

Wire web version: 2017-01-23
Firefox version: 50.1.0
Both on Ubuntu 16.04

**Comment by ffflorian** [comment] 2017-01-26 16:58
I cannot confirm this - at least on Debian 8 with Firefox 51.0 it works as intended. Have you tried it with Firefox 51.0? And could you provide a screenshot and/or a log?

![screenshot](https://cloud.githubusercontent.com/assets/5497598/22341372/d78f0bee-e3f0-11e6-8835-7356592be117.png)


Wire web version: Version 2017-01-23
Firefox version: 51.0 (64-bit)
Both on Debian 8.

**Comment by MakisH** [comment] 2017-01-26 17:20
We just tried again and it worked. But please don't close this yet, it has happened to me again some times, I will try to observe it. Probably it doesn't really depend on which platform calls though.

How can I get a log?

**Comment by gregor** [comment] 2017-01-27 15:28
Can you check if your non working calls on Firefox are related to this issue #687

**Comment by MakisH** [comment] 2017-01-28 19:22
Indeed, it is related to #687!

How to reproduce/what happens (Alice and Bob both have Firefox on Ubuntu):
1. Bob calls Alice (audio or video call, doesn't matter).
2. Alice answers and they talk.
3. Bob ends the conversation.
4. As stated in #687, the buttons to place a call disappear from Alice's page.
5. Bob calls again.
6. This time, no buttons to answer the call are shown in Alice's page.

Follow-up:
7. Bob ends the (unanswered) call.
8. Alice now can see that Bob called her and the "place a call" buttons reappear.

**Comment by gregor** [comment] 2017-01-29 18:06
Thank you very much for verifying my suspicion. I will thus close this issue and continue to track it in #687.

**Closed as completed by gregor** 2017-01-29 18:06 UTC
Labels: type: bug / fix 🐞
